/************************************************************
*Troca de conteúdos na parte de contactos para os usuários  *
************************************************************/
var contacto1 = document.getElementById('contacto1');
var contacto2 = document.getElementById('contacto2');
var contacto3 = document.getElementById('contacto3');
var contacto4 = document.getElementById('contacto4');
var contacto5 = document.getElementById('contacto5');
var contacto6 = document.getElementById('contacto6');
var contacto7 = document.getElementById('contacto7');
var contacto8 = document.getElementById('contacto8');
var contacto9 = document.getElementById('contacto9');
var contacto10 = document.getElementById('contacto10');

var content1 = document.getElementById('content1');
var content2 = document.getElementById('content2');
var content3 = document.getElementById('content3');
var content4 = document.getElementById('content4');
var content5 = document.getElementById('content5');
var content6 = document.getElementById('content6');
var content7 = document.getElementById('content7');
var content8 = document.getElementById('content8');
var content9 = document.getElementById('content9');
var content10 = document.getElementById('content10');


function contactoShow1(){
    content1.style.transform = "translateX(0)";
    content1.style.display="block";
    content1.style.visibility="visible";
    content2.style.transform = "translateX(200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
    contacto1.classList.remove('tab__selected');
    contacto1.classList.add('tab__selected');
}

function contactoShow2(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(0)";
    content2.style.display="block";
    content2.style.visibility="visible";
    content3.style.transform = "translateX(200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto2.classList.add('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow3(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(0)";
    content3.style.display="block";
    content3.style.visibility="visible";
    content4.style.transform = "translateX(200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto3.classList.add('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow4(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(0)";
    content4.style.display="block";
    content4.style.visibility="visible";
    content5.style.transform = "translateX(200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto4.classList.add('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow5(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(0)";
    content5.style.display="block";
    content5.style.visibility="visible";
    content6.style.transform = "translateX(200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto5.classList.add('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow6(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(-200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(0)";
    content6.style.display="block";
    content6.style.visibility="visible";
    content7.style.transform = "translateX(200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto6.classList.add('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow7(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(-200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(-200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(0)";
    content7.style.display="block";
    content7.style.visibility="visible";
    content8.style.transform = "translateX(200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto7.classList.add('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow8(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(-200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(-200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(-200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(0)";
    content8.style.display="block";
    content8.style.visibility="visible";
    content9.style.transform = "translateX(200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto8.classList.add('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow9(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(-200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(-200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(-200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(-200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(0)";
    content9.style.display="block";
    content9.style.visibility="visible";
    content10.style.transform = "translateX(200%)";
    content10.style.display="none";
    content10.style.visibility="hidden";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto9.classList.add('tab__selected');
    contacto10.classList.remove('tab__selected');
}

function contactoShow10(){
    content1.style.transform = "translateX(-200%)";
    content1.style.display="none";
    content1.style.visibility="hidden";
    content2.style.transform = "translateX(-200%)";
    content2.style.display="none";
    content2.style.visibility="hidden";
    content3.style.transform = "translateX(-200%)";
    content3.style.display="none";
    content3.style.visibility="hidden";
    content4.style.transform = "translateX(-200%)";
    content4.style.display="none";
    content4.style.visibility="hidden";
    content5.style.transform = "translateX(-200%)";
    content5.style.display="none";
    content5.style.visibility="hidden";
    content6.style.transform = "translateX(-200%)";
    content6.style.display="none";
    content6.style.visibility="hidden";
    content7.style.transform = "translateX(-200%)";
    content7.style.display="none";
    content7.style.visibility="hidden";
    content8.style.transform = "translateX(-200%)";
    content8.style.display="none";
    content8.style.visibility="hidden";
    content9.style.transform = "translateX(-200%)";
    content9.style.display="none";
    content9.style.visibility="hidden";
    content10.style.transform = "translateX(0)";
    content10.style.display="block";
    content10.style.visibility="visible";
    contacto1.classList.remove('tab__selected');
    contacto2.classList.remove('tab__selected');
    contacto3.classList.remove('tab__selected');
    contacto4.classList.remove('tab__selected');
    contacto5.classList.remove('tab__selected');
    contacto6.classList.remove('tab__selected');
    contacto7.classList.remove('tab__selected');
    contacto8.classList.remove('tab__selected');
    contacto9.classList.remove('tab__selected');
    contacto10.classList.remove('tab__selected');
    contacto10.classList.add('tab__selected');
}

contacto1.addEventListener('click', contactoShow1);
contacto2.addEventListener('click', contactoShow2);
contacto3.addEventListener('click', contactoShow3);
contacto4.addEventListener('click', contactoShow4);
contacto5.addEventListener('click', contactoShow5);
contacto6.addEventListener('click', contactoShow6);
contacto7.addEventListener('click', contactoShow7);
contacto8.addEventListener('click', contactoShow8);
contacto9.addEventListener('click', contactoShow9);
contacto10.addEventListener('click', contactoShow10);